version: '3.8'

services:
  fx_nginx:
    build: .
    ports:
      - "80:80"
    networks: 
      - frontend
      #- backend
  #Runs Dockerfile build & Marks network to use 
  webapp:
    image: tutum/hello-world
    ports:
      - "80"
    networks: 
      - frontend
   #Pulls image and marks network to use
networks: 
  frontend:
#  backend:
