version: '3.8'

services:
  fx_nginx:
    build: .
    ports:
      - "80:80"
    networks: 
      - frontend
      - backend
  webapp:
    image: tutum/hello-world
    ports:
      - "80"
    networks: 
      - frontend

networks: 
  frontend:
  backend:
